config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :jobs

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :authenticate_user!

	# GET /jobs
	def index
		@jobs = Job.where(:user_id => current_user.id)
	end

	# GET /jobs/new
	def new
		@job = Job.new
	end

	# POST /jobs
	def create
		@job = Job.new(job_params)
		@job.user_id = current_user.id

		if @job.save 
			respond_to do |format|
				format.html { redirect_to jobs_url }
			end
		else
			format.html { render :new }
		end
	end

	# GET /jobs/:id/edit
	def edit
		@job = Job.find(params[:id])
	end

	# PATCH /jobs/:id
	def update
		@job = Job.find(params[:id])

		@job.update(job_params)

		if @job.save 
			respond_to do |format|
				format.html { redirect_to jobs_url }
			end
		else
			format.html { render :new }
		end
	end

	# DELETE /jobs/id
	def destroy
		Job.find(params[:id]).destroy
		redirect_to jobs_url
	end


	def job_params
		params.require(:job).permit(:company, :position, :link, :status, :notes)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for job do |f| %>
	<%= f.input :company %>
	<%= f.input :position %>
	<%= f.input :link %>
	<%= f.input :status %>
	<%= f.input :notes %>
	<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render partial: "form", locals: {job: @job} %>

app/views/jobs/index.html.erb
<h1>Job Opportunity Pipeline</h1>

<div class="row">
	<table class="table table-striped table-hover">
		<thead class="thead-inverse">
			<tr>
				<th>Company</td>
				<th>Position</td>
				<th>Link</td>
				<th>Status</td>
				<th>Notes</td>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @jobs.each do |job| %>
				<tr scope="row">
					<td><%= job.company %></td>
					<td><%= job.position %></td>
					<td>
						<% if job.link != "" %>
							<a href="<%= job.link %>">Link</a>
						<% else %>
							-
						<% end %>
					</td>
					<td><%= job.status %></td>
					<td><%= job.notes %></td>
					<td>
						<div class="btn-group" role="group" aria-label="Basic example">
							<%= link_to "Edit", edit_job_path(id: job.id), {class: "btn btn-default"} %>
							<%= link_to "Delete", job, {method: :delete, class: "btn btn-default btn-danger"} %>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="row">
	<%= link_to "New Job", new_job_path, class: "btn btn-primary" %>
</div>

app/views/jobs/new.html.erb
<h1>New</h1>

<%= render partial: "form", locals: {job: @job} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<div>
	<% if user_signed_in? %>
	  Signed in as <%= current_user.email %><br>
	  Not you? <%= link_to("Sign Out", destroy_user_session_path , :method => :delete) %>
	<% else %>
	  <%= link_to("Sign Up", new_user_registration_path) %> or <%= link_to("Sign In", new_user_session_path) %>
	<% end %>
</div>

<%= yield %>

</div>

</body>
</html>